### ISSUE TITLE
Request: Support comments to pull requests as well as issues

### ISSUE THREAD

**Issue by tomwillis608** [security-alert/security-alert#36]
On the [npm page](https://www.npmjs.com/package/@security-alert/sarif-to-comment) for `@security-alert/sarif-to-comment` the text says the module will "Post comment to GitHub issue/pull requests." However, pulls are not supported, only issues.  My request would be to add support for both pull requests and issues in `sarif-to-comment`.

**Comment by azu** [comment]
Fmm, I thought that `octokit.rest.issues.createComment` also support PR.
It look like something wrong.

- https://docs.github.com/en/rest/issues/comments#create-an-issue-comment
- > To add a regular comment to a pull request timeline, see "Create an issue comment." 
  > https://octokit.github.io/rest.js/v18#pulls-create-review-comment

https://github.com/security-alert/security-alert/blob/4aec913fb8027d0a4c68e56874f731a6dfbc38b0/packages/sarif-to-comment/src/index.ts#L87-L94
https://github.com/security-alert/security-alert/blob/4aec913fb8027d0a4c68e56874f731a6dfbc38b0/packages/sarif-to-comment/src/issue-comment.ts#L26-L28

**Comment by tomwillis608** [comment]
The problem happens in the issuePattern test in index.ts.
I will add PR in a few minutes.

**Comment by tomwillis608** [comment]
Hopefully fixed by https://github.com/security-alert/security-alert/pull/37
My reading of the octokit docs also suggests that the existing `issueComment` code should work for a PR as well as an issue.

**Comment by azu** [comment]
Thanks.
https://github.com/security-alert/security-alert/releases/tag/v1.10.4
