### ISSUE TITLE
FEAT: add an error exit code mode

### ISSUE THREAD

**Issue by Gby56** [security-alert/security-alert#40]
Since https://github.com/returntocorp/semgrep/issues/5075 does not support severity filtering AND will always throw an error, or you have to ignore it with ` || true` in your ci script, I think it would be cool to add a `--fail-on-finding` that can be combined with the severity filtering we already have
That way security-alert can become a more useful CI/CD tool to fail PR checks, without the need for the scanning tool to support severity filtering + failure throwing

**Comment by azu** [comment]
A similar idea.
https://github.com/reviewdog/reviewdog#exit-codes
https://github.com/reviewdog/reviewdog/issues/856

I like `--fail-on=<severity level>`.
e.g. `--fail-on=WARNING`

**Comment by Gby56** [comment]
Yes ! Reviewdog is actually as good as security-alert for PRs, even better, I thought about contributing there too
I'll use the format for --fail-on then, it might make some weird behavior with `--severity` though
