### ISSUE TITLE
Failon mode is not throwing an exit error code

### ISSUE THREAD

**Issue by Gby56** [security-alert/security-alert#43]
@azu I think the [error throwing](https://github.com/security-alert/security-alert/blob/e69657332a4990d189af422e72998eb05e61b9d4/packages/sarif-to-comment/src/cli.ts#L172) is not working, I have tested the cli in my github actions and the step is not failing, also on my local machine I see that zsh is not getting an error code exit
```
 gabrielmarquet@xxxxxx ~/Desktop/semgrep_fun  npx @security-alert/sarif-to-comment semgrep.sarif \
  --commentUrl "https://github.com/xxxxxx/issues/45" \
  --sarifContentOwner xx \
  --sarifContentRepo sxxx \
  --sarifContentBranch test-vuln --failon error --title "Semgrep Report" --token --action --simple
Error: https://github.com/xx/xxxx/pull/45#issuecomment-xxxx
Failing ! An issue with severity error was found.
    at /Users/gabrielmarquet/Desktop/semgrep_fun/node_modules/@security-alert/sarif-to-comment/lib/cli.js:209:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 gabrielmarquet@xxxx  ~/Desktop/semgrep_fun  echo $?
0
```

the `echo $?` should not be 0

**Comment by azu** [comment]
https://github.com/security-alert/security-alert/blob/e69657332a4990d189af422e72998eb05e61b9d4/packages/sarif-to-comment/bin/cmd.js#L8
Ah, `process.exit(1)` is missing in here.

**Comment by Gby56** [comment]
:( I thought meow would do that properly automatically
