### ISSUE TITLE
use of sarif-to-markdown

### ISSUE THREAD

**Issue by KrawczowaKris** [security-alert/security-alert#76]
Hello,

I'm trying to convert a sarif file to markdown text using `sarif-to-markdown` but I'm getting the following error:

```
$ npm install @security-alert/sarif-to-markdown               

added 4 packages in 234ms

$ npx @security-alert/sarif-to-markdown input.sarif
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /home/root/.npm/_logs/2024-02-22T19_10_07_331Z-debug-0.log
```

What could this be causing and how to use this package correctly?

**Comment by azu** [comment]
[@security-alert/sarif-to-markdown](https://github.com/security-alert/security-alert/tree/master/packages/sarif-to-markdown) does not includes a CLI.
Therefore, even if you execute it in NPX, it will be an error.

It may be a good idea to use [`util.parseArgs`](https://nodejs.org/api/util.html#utilparseargsconfig) to add CLI.
